finapp/routes/dashboard.py
from unicodedata import category
from finapp.queries import (
    budget_queries,
    category_queries,
    dashboard_queries,
    transaction_queries,
)
from flask import Blueprint, render_template, request
from flask_login import login_required
from finapp.utils.Sqids import sqids
from finapp.utils import helpers


dashboard_bp = Blueprint("dashboard_bp", __name__)


@dashboard_bp.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    dashboard_queries.get_spending_by_budget_and_month()
    start_date = transaction_queries.get_first_transaction_date()
    return render_template("dashboard.newest.html", startDate=start_date)


@dashboard_bp.route("/api/get_net_worth_data", methods=["GET"])
@login_required
def api_get_net_worth_data():
    data = dashboard_queries.get_net_worth_data()

    return {"data": data}


@dashboard_bp.route("/api/get_budget_totals_by_date", methods=["GET"])
@login_required
def api_get_budget_totals_by_date():
    lc_data, start_date_, end_date = dashboard_queries.get_line_chart_data()

    return {"data": lc_data, "start_date": start_date_, "end_date": end_date}


@dashboard_bp.route("/api/get_spending_by_budget", methods=["GET"])
@login_required
def api_get_spending_by_budget():
    month = request.args.get("month", 0, type=int)
    year = request.args.get("year", 0, type=int)
    ytd = request.args.get("ytd") == "true"

    data = helpers.net_spending(month, year, ytd)

    return data


@dashboard_bp.get("/api/get_spending_by_month")
@login_required
def api_get_spending_by_month():
    budgets, income, spending = dashboard_queries.get_spending_by_budget_and_month()

    budgets = {b.sqid_id(): b.to_dict() for b in budgets}

    for row in spending:
        row["budget_id"] = sqids.encode_one(row["budget_id"])
    for row in income:
        row["budget_id"] = sqids.encode_one(row["budget_id"])

    return {"budgets": budgets, "spending": spending, "income": income}


@dashboard_bp.get("/api/get_spending_by_category")
@login_required
def api_get_spending_by_category():
    current_date = request.args.get("date")
    interval = request.args.get("interval", default="monthly")

    data = helpers.spending_by_category(
        current_date_str=current_date, interval=interval
    )
    categories = {c.sqid_id(): c.to_dict() for c in category_queries.get_categories()}
    data = {sqids.encode_one(key): val for key, val in data.items()}

    return {"data": data, "categories": categories}

finapp/routes/preferences.py
from flask import Blueprint, render_template
from flask_login import login_required

preferences_bp = Blueprint("preferences_bp", __name__)


@preferences_bp.route("/preferences", methods=["GET"])
@login_required
def preferences():
    return render_template("preferences.html")

finapp/routes/simplefin.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from finapp.queries import simplefin_queries, transaction_queries
from finapp.utils import simplefin as simplefin_helpers, helpers
import os
from finapp.utils.Sqids import sqids


simplefin_bp = Blueprint("simplefin_bp", __name__)


@simplefin_bp.get("/simplefin")
@login_required
def simplefin():
    force = request.args.get("force", type=bool, default=False)

    credentials = simplefin_queries.get_simplefin_credentials()

    if force:
        return render_template(
            "simplefin.html", credentials=credentials.to_dict() if credentials else {}
        )

    if credentials:
        return redirect(url_for("simplefin_bp.simplefin_accounts"))

    return render_template(
        "simplefin.html", credentials=credentials.to_dict() if credentials else {}
    )


@simplefin_bp.get("/simplefin_accounts")
@login_required
def simplefin_accounts():
    accounts = simplefin_queries.get_simplefin_accounts()
    credentials = simplefin_queries.get_simplefin_credentials()

    return render_template(
        "simplefin_accounts.html",
        accounts=[a.to_dict() for a in accounts],
        credentials=credentials.to_dict() if credentials else {},
    )


@simplefin_bp.get("/api/get_pending_transaction")
@login_required
def api_get_pending_transaction():
    pending_transactions = [
        pt.to_dict() for pt in simplefin_queries.get_pending_transactions()
    ]

    return dict(pending_transactions=pending_transactions)


@simplefin_bp.post("/delete_pending_transaction/<int:id>")
@login_required
def delete_pending_transaction(id):
    simplefin_queries.delete_pending_transaction(id=id)

    pending_transactions = [
        pt.to_dict() for pt in simplefin_queries.get_pending_transactions()
    ]

    return dict(pending_transactions=pending_transactions)


@simplefin_bp.post("/convert_pending_transtion/<int:id>")
@login_required
def convert_pending_transaction(id):
    user_id = sqids.decode_one(request.form.get("user")) or current_user.id
    budget_id = sqids.decode_one(request.form.get("budget"))
    name = request.form.get("name")
    amount = request.form.get("amount", type=float, default=0.0)
    str_date = request.form.get("date")
    date = helpers.get_date_from_string(str_date)
    return_transactions = request.form.get("return-transactions")
    return_transactions = return_transactions and return_transactions == "True"

    return_transaction = request.form.get("return-transaction")
    return_transaction = return_transaction and return_transaction == "True"

    categories = sqids.decode_list(request.form.getlist("categories"))

    transaction_id = simplefin_queries.convert_pending_transaction(
        user_id=user_id,
        name=name,
        amount=amount,
        t_date=date,
        budget_id=budget_id,
        categories=categories,
        pending_transaction_id=id,
    )

    transaction = transaction_queries.get_transaction(
        transaction_id=transaction_id, include_budget=True
    )
    pending_transactions = [
        pt.to_dict() for pt in simplefin_queries.get_pending_transactions()
    ]

    return dict(
        transaction=transaction.to_dict(), pending_transactions=pending_transactions
    )


@simplefin_bp.post("/claim_simplefin_token")
@login_required
def claim_simplefin_token():
    setup_token = request.form.get("setup_token")

    username, password = simplefin_helpers.claim_simplefin_token(setup_token)

    simplefin_queries.create_simplefin_credentials(username=username, password=password)
    credentials = simplefin_queries.get_simplefin_credentials()

    simplefin_helpers.sync_simplefin(credentials=credentials)

    return redirect(url_for("simplefin_bp.simplefin"))


@simplefin_bp.post("/delete_simplefin_credentials")
@login_required
def delete_simplefin_credentials():
    simplefin_queries.delete_simplefin_credentials()

    return redirect(url_for("simplefin_bp.simplefin"))


@simplefin_bp.get("/sync_simplefin_transactions")
@login_required
def sync_simplefin_transactions():
    credentials = simplefin_queries.get_simplefin_credentials()
    if not credentials:
        flash("No SimpleFIN Credentials", "danger")
        return redirect(url_for("simplefin_bp.simplefin"))
    else:
        simplefin_helpers.sync_simplefin_transactions(credentials=credentials)

    return redirect(url_for("simplefin_bp.simplefin_accounts"))


@simplefin_bp.get("/sync_simplefin_account_balances")
@login_required
def sync_simplefin_account_balances():
    credentials = simplefin_queries.get_simplefin_credentials()
    if not credentials:
        flash("No SimpleFIN Credentials", "danger")
        return redirect(url_for("simplefin_bp.simplefin"))
    else:
        simplefin_helpers.sync_simplefin_account_balances(credentials=credentials)

    return redirect(url_for("simplefin_bp.simplefin_accounts"))


@simplefin_bp.get("/sync_simplefin")
@login_required
def sync_simplefin():
    credentials = simplefin_queries.get_simplefin_credentials()
    if not credentials:
        flash("No SimpleFIN Credentials", "danger")
        return redirect(url_for("simplefin_bp.simplefin"))
    else:
        simplefin_helpers.sync_simplefin(credentials=credentials)

    return redirect(url_for("simplefin_bp.simplefin_accounts"))


@simplefin_bp.get("/api/sync_simplefin_transactions")
@login_required
def api_sync_simplefin_transactions():
    credentials = simplefin_queries.get_simplefin_credentials()
    if not credentials:
        simplefin_helpers.sync_simplefin_transactions(credentials=None)
    else:
        simplefin_helpers.sync_simplefin_transactions(credentials=credentials)

    pending_transactions = [
        pt.to_dict() for pt in simplefin_queries.get_pending_transactions()
    ]

    return dict(pending_transactions=pending_transactions)


@simplefin_bp.post("/update_account_access_type/<string:id>")
@login_required
def update_account_access_type(id):
    should_sync_transactions = request.form.get(
        "sync_transactions", type=int, default=2
    )

    simplefin_queries.update_account_access_type(
        id=id, access_type=should_sync_transactions
    )

    account = simplefin_queries.get_simplefin_account(id=id)

    return dict(access_type=account.access_type)


@simplefin_bp.post("/update_account_name/<string:id>")
@login_required
def update_account_name(id):
    name = request.form.get("name", type=str)

    simplefin_queries.update_account_name(id=id, name=name)

    account = simplefin_queries.get_simplefin_account(id=id)

    return dict(name=account.name)


@simplefin_bp.get("/api/update_all_accounts_and_transactions")
def update_all_accounts_and_transactions():
    key = request.args.get("key")
    if key != os.environ.get("SIMPLEFIN_KEY"):
        return dict(success=False)

    simplefin_helpers.update_all_accounts_and_transactions(key=key)

    return dict(success=True)

finapp/routes/viewbudget.py
from finapp.queries import (
    budget_queries,
    category_queries,
    shared_budget_queries,
    transaction_queries,
    user_queries,
)
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from finapp.utils import helpers
import json
from finapp.utils.Sqids import sqids

viewbudget_bp = Blueprint("viewbudget_bp", __name__)


@viewbudget_bp.get("/view_budget/<string:sqid>/")
@viewbudget_bp.get("/view_budget/<string:sqid>/<string:name>")
@login_required
def view_budget(sqid, name=None):
    budget_id = sqids.decode_one(sqid)

    page = request.args.get("page", 1, type=int)

    month = request.args.get("month", 0, type=int)
    year = request.args.get("year", 0, type=int)
    ytd = request.args.get("ytd") == "true"

    budget = budget_queries.get_budget(budget_id=budget_id)
    budgets = [b.to_dict() for b in budget_queries.get_budgets(active_only=True)]

    if ytd:
        transactions, total, page, num_pages = (
            transaction_queries.get_transactions_for_year(
                budget_id=budget.id, year=year, page=page, paginate=True
            )
        )
    elif month:
        transactions, total, page, num_pages = (
            transaction_queries.get_transactions_for_month(
                budget_id=budget.id, month=month, year=year, page=page, paginate=True
            )
        )
    else:
        transactions, total, page, num_pages = transaction_queries.get_transactions(
            budget_id=budget.id, page=page, paginate=True
        )

    budget = budget.to_dict()
    transactions = [t.to_dict() for t in transactions]

    categories = category_queries.get_categories()
    categories = [c.to_dict() for c in categories]

    return render_template(
        "viewbudget.html",
        budget=budget,
        transactions=transactions,
        budgets=budgets,
        categories=categories,
        total=total,
        page=page,
        num_pages=num_pages,
    )


@viewbudget_bp.get("/get_page/<string:sqid>/")
@viewbudget_bp.get("/get_page/<string:sqid>/<string:name>")
@login_required
def get_page(sqid, name=None):
    page = request.args.get("page", -1, type=int)

    if page < 1:
        return {"sucess": False}

    budget_id = sqids.decode_one(sqid)

    month = request.args.get("month", 0, type=int)
    year = request.args.get("year", 0, type=int)
    ytd = request.args.get("ytd") == "true"
    sort_by = request.args.get("sort")
    try:
        sort_by = json.loads(sort_by)
    except:
        sort_by = None

    budget = budget_queries.get_budget(budget_id=budget_id)

    if ytd:
        transactions, total, page, num_pages = (
            transaction_queries.get_transactions_for_year(
                budget_id=budget_id,
                year=year,
                page=page,
                sort_by=sort_by,
                paginate=True,
            )
        )
    elif month:
        transactions, total, page, num_pages = (
            transaction_queries.get_transactions_for_month(
                budget_id=budget_id,
                month=month,
                year=year,
                page=page,
                sort_by=sort_by,
                paginate=True,
            )
        )
    else:
        transactions, total, page, num_pages = transaction_queries.get_transactions(
            budget_id=budget_id, page=page, sort_by=sort_by, paginate=True
        )

    transactions = [t.to_dict() for t in transactions]

    return {
        "page": page,
        "transactions": transactions,
        "total": total,
        "num_pages": num_pages,
        "budget_total": budget.total,
    }


@viewbudget_bp.get("/search/<string:sqid>/")
@viewbudget_bp.get("/search/<string:sqid>/<string:name>")
@login_required
def search(sqid, name=None):
    budget_id = sqids.decode_one(sqid)

    start_date = request.args.get("startDate")
    end_date = request.args.get("endDate")
    amount = request.args.get("amount")
    min_amount = request.args.get("minAmount")
    max_amount = request.args.get("maxAmount")
    name = request.args.get("name")
    if name:
        name = json.loads(name)
    else:
        name = []
    categories = sqids.decode_list(request.form.getlist("categories"))
    page = request.args.get("page", -1, type=int)

    month = request.args.get("month", 0, type=int)
    year = request.args.get("year", 0, type=int)
    ytd = request.args.get("ytd") == "true"

    sort_by = request.args.get("sort")

    transactions, total, page, num_pages, search_sum = helpers.search_for(
        budget_id=budget_id,
        name=name,
        categories=categories,
        start_date=start_date,
        end_date=end_date,
        amount=amount,
        min_amount=min_amount,
        max_amount=max_amount,
        page=page,
        month=month,
        year=year,
        ytd=ytd,
        sort_by=sort_by,
    )

    transactions = [t.to_dict() for t in transactions]

    return {
        "page": page,
        "transactions": transactions,
        "total": total,
        "num_pages": num_pages,
        "search_sum": search_sum,
    }

finapp/routes/viewtransactions.py
from finapp.queries import (
    category_queries,
    budget_queries,
    transaction_queries,
)
from flask import Blueprint, render_template, request, stream_with_context, Response
from flask_login import login_required
import json


viewtransactions_bp = Blueprint("viewtransactions_bp", __name__)


@viewtransactions_bp.get("/")
@viewtransactions_bp.get("/view_transactions")
@login_required
def view_transactions():
    transactions, total = transaction_queries.get_recent_transactions(
        limit=100, include_total=True
    )
    transactions = [t.to_dict() for t in transactions]

    budgets = budget_queries.get_budgets(active_only=True)
    budgets = [b.to_dict() for b in budgets]

    categories = category_queries.get_categories()
    categories = [c.to_dict() for c in categories]

    return render_template(
        "viewtransactions.html",
        transactions=transactions,
        budgets=budgets,
        categories=categories,
        total=total,
    )


@viewtransactions_bp.get("/api/get_transactions")
@login_required
def api_get_transactions():
    include_budgets = request.args.get("includeBudgets")
    include_budgets = include_budgets and include_budgets == "True"

    transactions, _ = transaction_queries.get_recent_transactions()
    transactions = [t.to_dict() for t in transactions]

    if include_budgets:
        budgets = [b.to_dict() for b in budget_queries.get_budgets()]

        return dict(transactions=transactions, budgets=budgets)

    return dict(transactions=transactions)


@viewtransactions_bp.get("/api/get_transactions_stream")
@login_required
def api_get_transactions_stream():
    include_budgets = request.args.get("includeBudgets")
    include_budgets = include_budgets and include_budgets == "True"

    def generate():
        yield '{"transactions": ['

        prev_transaction = None
        transactions, _ = transaction_queries.get_recent_transactions()
        for t in transactions:
            if prev_transaction is not None:
                yield json.dumps(prev_transaction.to_dict()) + ", "

            prev_transaction = t

        yield json.dumps(prev_transaction.to_dict()) + "]"

        if include_budgets:
            yield ', "budgets": ['

            prev_budget = None
            budgets = budget_queries.get_budgets()
            for b in budgets:
                if prev_budget is not None:
                    yield json.dumps(prev_budget.to_dict()) + ", "

                prev_budget = b

            yield json.dumps(prev_budget.to_dict()) + "]"

        yield "}"

    return Response(
        response=stream_with_context(generate()),
        mimetype="application/json",
    )

finapp/templates/addpaycheck.html
{% extends "base.html" %} {% block title %}Add Paycheck{% endblock title %} {%
block addtransaction %}active{% endblock addtransaction %} {% block backButton
%}<nb-back-button></nb-back-button>{% endblock backButton %} {% block head %}

<script src="/static/js/nb-add-paycheck.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-add-paycheck
  class="main-card"
  budgets='{{ budgets|tojson }}'
  paychecks='{{ paychecks|tojson }}'
></nb-add-paycheck>

{% endblock content %}

finapp/templates/dashboard.newest.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock title %} {%
block dashboard %}active{% endblock dashboard %} {% block backButton
%}<nb-back-button></nb-back-button>{% endblock backButton %} {% block head %}
<script src="/static/js/nb-dashboard.mjs" type="module"></script>

<script>
  const GET_NET_WORTH_DATA_URL =
    "{{ url_for('dashboard_bp.api_get_net_worth_data') }}";
  const GET_LINE_CHART_DATA_URL =
    "{{ url_for('dashboard_bp.api_get_budget_totals_by_date') }}";
  const GET_SPENDING_BY_MONTH_URL =
    "{{ url_for('dashboard_bp.api_get_spending_by_month') }}";
  const GET_BUDGET_SPENDING_URL =
    "{{ url_for('dashboard_bp.api_get_spending_by_budget') }}";
  const GET_CATEGORY_SPENDING_URL =
    "{{ url_for('dashboard_bp.api_get_spending_by_category') }}";

  const START_DATE = "{{ startDate }}";
</script>

<link
  rel="preload"
  href="{{ url_for('dashboard_bp.api_get_net_worth_data') }}"
  as="fetch"
  crossorigin="anonymous"
/>
<link
  rel="preload"
  href="{{ url_for('dashboard_bp.api_get_budget_totals_by_date') }}"
  as="fetch"
  crossorigin="anonymous"
/>
<!-- <link
  rel="preload"
  href="{{ url_for('dashboard_bp.api_get_spending_by_budget') }}"
  as="fetch"
  crossorigin="anonymous"
/>
<link
  id="categorySpendingLink"
  rel="preload"
  href="{{ url_for('dashboard_bp.api_get_spending_by_category') }}"
  as="fetch"
  crossorigin="anonymous"
/> -->

{% endblock head %} {% block content %}

<nb-dashboard></nb-dashboard>

{% endblock content %}

finapp/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock title %} {% block
login %}active{% endblock login %} {% block head %}

<script src="/static/js/nb-login.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-login
  class="auth-card"
  {%
  if
  email
  %}email="{{ email }}"
  {%
  endif
  %}
></nb-login>

{% endblock content %}

finapp/templates/oauth.html
{% extends "base.html" %}

<!-- <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script>
  (function () {
    let linkToken = localStorage.getItem("link_token");
    console.log(linkToken);
    let handler = Plaid.create({
      token: linkToken,
      receivedRedirectUri: window.location.href,
      onSuccess: function (public_token) {
        postRequest(
          "/api/set_access_token",
          { public_token: public_token },
          function (data) {
            location.href = "https://example.com";
          }
        );
      },
    });

    handler.open();
  })();
</script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script>
  (function ($) {
    var linkToken = localStorage.getItem("link_token");
    var handler = Plaid.create({
      token: linkToken,
      receivedRedirectUri: window.location.href,
      onSuccess: function (public_token) {
        $.post(
          "/api/set_access_token",
          { public_token: public_token },
          function (data) {
            location.href = "https://example.com";
          }
        );
      },
    });
    handler.open();
  })(jQuery);
</script>

finapp/templates/password_request.html
{% extends "base.html" %} {% block title %}Password Reset Request{% endblock
title %} {% block head %}

<script src="/static/js/nb-password-reset-request.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-password-reset-request
  class="auth-card"
  email="{{ email }}"
></nb-password-reset-request>

{% endblock content %}

finapp/templates/preferences.html
{% extends "base.html" %} {% block title %}Preferences{% endblock title %} {%
block preferences %}active{% endblock preferences %} {% block backButton %}

<nb-back-button></nb-back-button>

{% endblock backButton %} {% block head %}

<script src="/static/js/nb-preferences.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-preferences class="main-card"></nb-preferences>

{% endblock content %}

finapp/templates/profile.html
{% extends "base.html" %} {% block title %}Profile{% endblock title %} {% block
profile %}active{% endblock profile %} {% block backButton %}

<nb-back-button></nb-back-button>

{% endblock backButton %} {% block head %}

<script src="/static/js/nb-profile.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-profile
  class="auth-card"
  username="{{ username }}"
  email="{{ email }}"
></nb-profile>

{% endblock content %}

finapp/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock title %} {% block
head %}

<script src="/static/js/nb-signup.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-signup class="auth-card" email="{{ email }}"></nb-signup>

{% endblock content %}

finapp/templates/simpleFin.html
{% extends "base.html" %} {% block title %}SimpleFIN Setup{% endblock title %}{%
block backButton %}

<nb-back-button></nb-back-button>

{% endblock backButton %} {% block head %}
<script>
  const CLAIM_SIMPLEFIN_TOKEN_URL =
    "{{ url_for('simplefin_bp.claim_simplefin_token') }}";
  const DELETE_SIMPLEFIN_CREDENTIALS_URL =
    "{{ url_for('simplefin_bp.delete_simplefin_credentials') }}";
</script>

<script src="/static/js/nb-simplefin.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-simplefin
  class="main-card"
  credentials='{{ credentials|tojson }}'
></nb-simplefin>

{% endblock content %}

finapp/templates/simplefin_accounts.html
{% extends "base.html" %} {% block title %}External Accounts{% endblock title
%}{% block backButton %}

<nb-back-button></nb-back-button>

{% endblock backButton %} {% block head %}
<script>
  const SYNC_SIMPLEFIN_ACCOUNT_BALANCES_URL =
    "{{ url_for('simplefin_bp.sync_simplefin_account_balances') }}";
  const SYNC_SIMPLEFIN_URL = "{{ url_for('simplefin_bp.sync_simplefin') }}";
  const SIMPLEFIN_CREDENTIALS_URL = "{{ url_for('simplefin_bp.simplefin') }}";
</script>

<script src="/static/js/nb-simplefin-accounts.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-simplefin-accounts
  class="main-card"
  accounts='{{ accounts|tojson }}'
  credentials='{{ credentials|tojson }}'
></nb-simplefin-accounts>

{% endblock content %}

finapp/templates/viewbudget.html
{% extends "base.html" %} {% block title %}{{ budget.name }}{% endblock title %}
{% block backButton %}<nb-back-button></nb-back-button>{% endblock backButton %}
{% block head %}
<script>
  const GET_PAGE_URL =
    "{{ url_for('viewbudget_bp.get_page', sqid=budget.id) }}";
  const SEARCH_PAGE_URL =
    "{{ url_for('viewbudget_bp.search', sqid=budget.id) }}";
  const BUDGETS = {{ budgets|tojson }};
</script>
<script src="/static/js/nb-view-budget.mjs" type="module"></script>
{% endblock head %} {% block content %}

<nb-view-budget
  budget='{{ budget|tojson }}'
  transactions='{{ transactions|tojson }}'
  categories='{{ categories|tojson }}'
  currentPage="{{ page }}"
  numPages="{{ num_pages }}"
  numTransactions="{{ total }}"
></nb-view-budget>

{% endblock content %}

finapp/templates/viewbudgets.html
{% extends "base.html" %} {% block title %}Home{% endblock title %} {% block
head %}

<script src="/static/js/nb-view-budgets.mjs" type="module"></script>

{% endblock head %} {% block content %}

<nb-view-budgets
  total="{{ total }}"
  budgets='{{ budgets|tojson }}'
></nb-view-budgets>

{% endblock content %}

finapp/templates/viewtransactions.html
{% extends "base.html" %} {% block title %}Home{% endblock title %} {% block
head %}
<script>
  const VIEW_TRANSACTIONS_CONTENT_URL =
    "{{ url_for('viewtransactions_bp.api_get_transactions_stream') }}";
  const PENDING_TRANSACTIONS_URL =
    "{{ url_for('simplefin_bp.api_get_pending_transaction') }}";
  const API_SYNC_SIMPLEFIN_TRANSACTIONS_URL =
    "{{ url_for('simplefin_bp.api_sync_simplefin_transactions') }}";
</script>

<script src="/static/js/nb-view-transactions.mjs" type="module"></script>

<link
  rel="preload"
  href="{{ url_for('viewtransactions_bp.api_get_transactions_stream') }}"
  as="fetch"
  crossorigin="anonymous"
/>
<link
  rel="preload"
  href="{{ url_for('simplefin_bp.api_get_pending_transaction') }}"
  as="fetch"
  crossorigin="anonymous"
/>
{% endblock head %}{% block content %}

<nb-view-transactions
  transactions='{{ transactions|tojson }}'
  budgets='{{ budgets|tojson }}'
  categories='{{ categories|tojson }}'
  theme="{{ user_settings.settings.mode }}"
  total="{{ total }}"
></nb-view-transactions>

{% endblock content %}